export const MAP_ASSET_KEYS = Object.freeze({
    WORLD: 'WORLD',
    UNITS: 'UNITS',
    EFFECTS_SMALL: 'EFFECTS_SMALL',
    EFFECTS_LARGE: 'EFFECTS_LARGE',
});

export const MAIN_UI_ASSET_KEYS = Object.freeze({
    SELECTED_UNIT: 'SELECTED_UNIT',
    MOVE: 'MOVE',
    ATTACK_MELEE: 'ATTACK_MELEE',
});

export const PANEL_UI_ASSET_KEYS = Object.freeze({
    HEALTHBAR_LEFT: 'HEALTHBAR_LEFT',
    HEALTHBAR_MIDDLE: 'HEALTHBAR_MIDDLE',
    HEALTHBAR_RIGHT: 'HEALTHBAR_RIGHT',
    SHADOW_LEFT: 'SHADOW_LEFT',
    SHADOW_MIDDLE: 'SHADOW_MIDDLE',
    SHADOW_RIGHT: 'SHADOW_RIGHT',
});
